# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-02-20 05:01:05
"""
import arcpy

def Model2():  # Model2

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Amador_County_New = "Amador_County_New"
    Drought = "Drought"

    # Process: Intersect (Intersect) (analysis)
    AmadorCoDrought = "C:\\California_County_Parcels\\California_County_Parcels\\California_County_Parcels.gdb\\AmadorCoDrought"
    arcpy.analysis.Intersect(in_features=[[Amador_County_New, ""], [Drought, ""]], out_feature_class=AmadorCoDrought, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\California_County_Parcels\California_County_Parcels\California_County_Parcels.gdb", workspace=r"C:\California_County_Parcels\California_County_Parcels\California_County_Parcels.gdb"):
        Model2()
